name: Link Check

on:
  pull_request:
    paths:
      - "docs/**"
  schedule:
    - cron: "0 7 * * 1"

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.9.0
        with:
          args: >-
            --no-progress
            --exclude-mail
            --accept 200,206,301,302,304,403,405,429
            --max-concurrency 4
            --timeout 20
            "docs/**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
